# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 21 * * *'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Europe/Kiev"
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build app
      run: dotnet build
    - name: Run app
      env:
        apiQuoteSet: ${{ secrets.APIQUOTE  }}
      run: dotnet run
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ./humanReadable ./json
        git commit ./humanReadable ./json --allow-empty -m "New day - new data!"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        tags: true
